
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 11;
  public static final int WHERE = 4;
  public static final int MAIOR = 7;
  public static final int MENOR = 6;
  public static final int STRING = 12;
  public static final int EOF = 0;
  public static final int NUMERO = 13;
  public static final int PONTOEVIRG = 9;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int SELECT = 2;
  public static final int FROM = 3;
  public static final int VIRG = 8;
  public static final int MUL = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "WHERE",
  "IGUAL",
  "MENOR",
  "MAIOR",
  "VIRG",
  "PONTOEVIRG",
  "MUL",
  "IDENT",
  "STRING",
  "NUMERO"
  };
}

